[programs.localnet]
example2 = "9CGVzJdcwUpvKbngPd2WEgHstJHfu5v1MESMeGPoKkf6"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/krish/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
